import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";
import { siteUrl } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service | Abuto Systems",
  description: "Website terms for browsing Abuto Systems and submitting product, service, consultation, or demo enquiries.",
  alternates: { canonical: `${siteUrl}/terms` },
};

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance and scope", content: <><p>These terms apply when you use the Abuto Systems website at <a href={siteUrl}>abutosystems.com</a>. By using the website, you agree to these terms. If you do not agree, please stop using it.</p><p>These are website terms. A separately signed or accepted agreement governs any software subscription, implementation, support, payment, service level, or data-processing arrangement and takes precedence for that service if the documents conflict.</p></> },
  { id: "about", title: "About the website", content: <><p>Abuto Systems is a technology brand through which digital products and technology services are offered. It operates from Kenya. The website provides general information about its work and products such as AskanPharma, a pharmacy management system. Website content is general information and may change; contact us to discuss a particular requirement.</p><p>Unless a separate agreement says otherwise, website content is not an offer to provide a particular product, service, price, feature, or delivery date.</p></> },
  { id: "enquiries", title: "Enquiries, consultations and demos", content: <><p>Information submitted through a contact or consultation form is a request for follow-up. Submitting a request does not by itself create a customer relationship or contract. Submitting a 21-day AskanPharma trial request asks us to help arrange setup; it does not automatically provision or start product access. We will contact you about the next steps.</p><p>When online AskanPharma demo scheduling is available on this website, the page checks Google Calendar availability for the selected date and time. Availability can change until the booking is confirmed. A demo is booked only when the website displays “Demo confirmed” after validating the request, reserving the slot, and verifying the Calendar event, attendee, and Google Meet link. If automatic scheduling cannot be completed, the submission remains a request and Abuto Systems will contact you to confirm next steps. A preferred time or request-received message alone does not confirm an appointment.</p></> },
  { id: "askanpharma", title: "AskanPharma and professional decisions", content: <><p>AskanPharma is business and pharmacy management software. Abuto Systems is not a pharmacy, healthcare provider, medical practitioner, or emergency service. The software and website do not provide medical advice, diagnosis, prescriptions, or clinical care.</p><p>Customers and users remain responsible for their business operations and any professional or clinical decisions they make. Product use, features, support, and data responsibilities are subject to separate customer agreements where applicable.</p></> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may use the website lawfully and for its intended informational and enquiry purposes. Do not misuse forms, submit knowingly false or unlawful material, attempt unauthorized access, interfere with website operation, introduce malicious code, or use the site in a way that infringes another person's rights.</p></> },
  { id: "intellectual-property", title: "Content and intellectual property", content: <><p>Unless stated otherwise, the website's text, visual design, and Abuto Systems branding are owned by or used with permission by Abuto Systems. You may view and print pages for personal or internal business reference. You may not reproduce, adapt, distribute, or commercially exploit website materials or marks without prior permission, except where law allows.</p><p>Names and marks belonging to third parties remain the property of their respective owners. If you send feedback or an enquiry, you retain ownership of your material; you permit us to use it as needed to respond to you and provide any service you request.</p></> },
  { id: "third-parties", title: "Third-party services and links", content: <p>The website may link to services such as WhatsApp or Cloudflare-powered security features. Those services are operated by third parties under their own terms and privacy notices. Abuto Systems does not control third-party websites and is not responsible for their content or operation.</p> },
  { id: "availability", title: "Availability and changes", content: <p>We may update, suspend, or remove website content or features to maintain or improve the site. We aim to keep information useful but do not promise uninterrupted access or that every page will always be complete, current, or error-free. A demo, trial, or product capability is available only when expressly offered and may be governed by separate terms.</p> },
  { id: "warranties", title: "Warranties and liability", content: <><p>The website is provided for general information and enquiry purposes. To the maximum extent permitted by applicable law, we exclude implied warranties that may lawfully be excluded.</p><p>Nothing in these terms excludes or limits a right, remedy, liability, or warranty that cannot lawfully be excluded or limited, including applicable statutory consumer protections. Subject to that rule, Abuto Systems is not responsible for loss caused by your use of or inability to use the website, or reliance on general website information, except where applicable law provides otherwise. These terms do not set a fixed monetary liability cap.</p></> },
  { id: "law", title: "Governing law and disputes", content: <p>These website terms are governed by the laws of Kenya. If a concern arises, please contact us first so we can try to resolve it informally. This does not restrict any right to bring a claim before a court or authority with jurisdiction, or any mandatory rights under applicable law.</p> },
  { id: "changes-contact", title: "Changes and contact", content: <><p>We may revise these terms by publishing an updated version on this page. The updated date will appear at the top. Continued use after a change takes effect constitutes use under the revised terms, subject to applicable law.</p><p>Questions about these terms can be sent to <a href="mailto:abutosystems@gmail.com">abutosystems@gmail.com</a>.</p></> },
];

export default function TermsPage() {
  return <LegalPage eyebrow="WEBSITE TERMS" title="Terms of Service" summary="The terms for using this website and requesting information about Abuto Systems products and services." sections={sections} />;
}
